//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SendingMessages
    {
        public long IdSent { get; set; }
        public long MessageId { get; set; }
        public System.DateTime Sent_Date { get; set; }
        public string Confirmation_Code { get; set; }
    
        public virtual tbl_Messages tbl_Messages { get; set; }
    }
}
